package game;

public enum TileType {
  PERMANENT_WALL,
  TEMPORARY_WALL,
  BOMB,
  BLAST,
  POWERUP_MEGA_BLAST_RANGE,
  POWERUP_HEALTH_UP,
  POWERUP_SPEED_BOOST,
  POWERUP_NO_BOMB_DROP_COOLDOWN,
  NONE
}
